### ISSUE TITLE
Immutable.js support?

### ISSUE THREAD

**Issue by IzumiSy** [bcherny/undux#10]
Currently, diffing process uses just triple equality. It is not suitable in using `Immutable#List`, because triple equality always returns true even between two different Lists. I would like to get a support of `is` method from Immutable.js for a right diffing.

ref: https://facebook.github.io/immutable-js/docs/#/is

For further understanding, here is the app on playground using Undux + Immutable.js
https://codesandbox.io/s/kw1vvv5mp5

The point I mentioned in this issue is happening in these lines in todoActions trying updating store but I can't.

```js
    markTodoDone(index: number) {
      const currentTodos = store.get("todos");
      const updatedTodos = currentTodos.update(index, (todo: Todo) => {
        const updatedTodo = todo;
        updatedTodo.markDone();
        return updatedTodo;
      });
      store.set("todos")(updatedTodos);
    }
```

**Comment by bcherny** [comment]
Excellent idea! I’m happy to do this one.

**Comment by bcherny** [comment]
Done in 3.2.0 - let me know how it works for you @IzumiSy!

**Comment by IzumiSy** [comment]
Thank you very much!!
