### ISSUE TITLE
TypeError when using Store.Container

### ISSUE THREAD

**Issue by zhaodong-wang** [bcherny/undux#157]
Hi, I was using undux and following the example here: https://undux.org/#quick-start

However, after the last step I got the following error:
```
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & ContainerProps<State>'.ts(2559)
```
When I am trying to wrap the whole application with the Container component I got back from createConnectedStore.

I remember I didn't get this error a couple of months ago. Is this because of any react changes? How should I fix it?

**Comment by ro-ka** [comment]
I’m having the exact same problem with React 18 & undux 5.

**Comment by bcherny** [comment]
Try again now -- types are all updated in 5.3.0.
