### ISSUE TITLE
Question: How to get this work with HMR, like Redux?

### ISSUE THREAD

**Issue by tpisto** [bcherny/undux#20]

**Comment by bcherny** [comment]
Some research:

- https://github.com/markerikson/react-redux-links/blob/master/webpack-advanced-techniques.md#hot-module-replacement
- https://github.com/reactjs/redux/issues/1940

**Comment by bcherny** [comment]
To clarify, Hot Module Reloading works out of the box. See demo here: https://github.com/bcherny/undux-hot-module-reloading-demo.
