### ISSUE TITLE
Investigate using React's new Context API

### ISSUE THREAD

**Issue by bcherny** [bcherny/undux#25]
Pros:

???

Cons:

- More complexity: 2 ways of doing things
- No support for old React versions
- Collisions if another component also uses context

https://reactjs.org/docs/context.html

**Comment by cjk** [comment]
One benefit of the new context-api is not having to pass props through component-hierarchies which is ugly, error-prone and increases coupling.
Not sure though how undux rectifies some of these problems to begin with.

**Comment by bcherny** [comment]
@cjk With Undux, you simply wrap each component that uses the store with `withStore`. This makes it clear where `store` is coming from, and exactly which components are connected.

See https://undux.org/#quick-start/2.
