### ISSUE TITLE
Can we safely support composing stores (like Redux)?

### ISSUE THREAD

**Issue by bcherny** [bcherny/undux#3]
If not, add explicit advice to the README about how to scale to lots of properties.

**Comment by danigb** [comment]
This is the first thing I miss from this (otherwise) nice library. How to scale?

**Comment by bcherny** [comment]
Hi @danigb! You have a few good options now:

1. Use a single store, and namespace properties in the store with a prefix.
2. Use multiple stores

I'm not sure Redux-style composition is very useful, so this feature would be more for parity and flexibility. Out of curiosity, how does composition help you with your use case?

**Comment by bcherny** [comment]
Tracking this in https://github.com/bcherny/undux/issues/32
