### ISSUE TITLE
Compared to MobX

### ISSUE THREAD

**Issue by andraz** [bcherny/undux#31]
How does this project compare to MobX / MST and where does it differ?

https://github.com/mobxjs/mobx
https://github.com/mobxjs/mobx-state-tree

**Comment by bcherny** [comment]
Hi @andraz! I haven't used MobX much, but from what I can tell:

- Undux has a lot fewer concepts than MobX. Undux doesn't have Actions, Computed Values, or Observables (every field on a store is observable).
- In MobX, Reaction are used for side effects like rendering and network requests. In Undux, Effects are used for things like network requests, but not rendering (rendering is done automatically). In Undux, Effects are full Rx observables, so you can do a lot more with them than you can in MobX.

At a high level, Undux is a lot simpler, and doesn't ship with advanced features like decorator support and derived values out of the box. That said, as I said I'm not a MobX user - maybe someone with more MobX experience can chime in too.
