### ISSUE TITLE
To use with react-router?

### ISSUE THREAD

**Issue by 1natsu172** [bcherny/undux#38]
`<Redirect>` of react-router-dom is not rendered successfully.
Maybe it seems like [this problem](https://reacttraining.com/react-router/web/guides/redux-integration) when combined with Redux.

I tried to write like this using recompose, 

```typescript
export const withStore = compose(withRouter, connect(store))
```

but compile error occurs with the callback argument of `withStore`.

`Type '{ children?: ReactNode; }' has no property 'store' and no string index signature.`

```typescript
export default withStore(({ store }) => {
  …
}
```

Is this a problem unique to undux?  Or is it a problem on react-router side?

I'm a typecript beginner and not familiar with the type, so I may be wrongfully wrong… If this is a childish question, I'm sorry. 🙇

**Comment by bcherny** [comment]
Hey @1natsu172! In general, Undux and React-Router are unrelated, and work well together.

Can you provide some more detail? If you can post some more code, or even better, a self-container repro case I'll be able to give more specific advice.

**Comment by bcherny** [comment]
Also, for basic usage, you don't need `compose` or `withRouter`. Here's a basic example:

```js
// store.js
import {connect, createStore} from 'undux'

const store = createStore({
  some: 'initial state'
})

export const withStore = connect(store)

// myComponent.js
import {withStore} from './store'

export const MyComponent = withStore(
  class extends React.Component {
    render(){...}
  }
)

// app.js
import {MyComponent} from './myComponent'
import {BrowserRouter as Router, Route} from 'react-router-dom'

export class App extends React.Component {
  render() {
    return <Router>
      <Route path='/foo' component={MyComponent} />
    </Router>
  }
}
```

**Comment by 1natsu172** [comment]
Thank you for your response. What I'm about to do is routing to secure private routes in the authentication state. 
like this, https://reacttraining.com/react-router/web/example/auth-workflow
In PrivateRoute component I'm trying to reference `isLoggedIn` state  from undux.

Just as you say normal routing is working without problems. Simply my PrivateRoute component may be wrong... 

I'd like to confirm once PrivateRoute works with a simple React configuration without undux. After confirmation, if there is still a problem with undux, will be opened issue again. I apologize to you for a fuss over.
