### ISSUE TITLE
Investigate adding support for Flow

### ISSUE THREAD

**Issue by bcherny** [bcherny/undux#4]

**Comment by ummahusla** [comment]
This should be implemented asap

**Comment by niieani** [comment]
These might prove helpful: 
- https://github.com/joarwilk/flowgen (TS typings to flow converter, not perfect, but a good start)
- https://github.com/niieani/typescript-vs-flowtype (syntax differences listed for manual corrections of the above)

**Comment by bcherny** [comment]
@niieani I'm familiar, but I don't think Flowgen supports mapped types.

Work in progress here https://github.com/bcherny/undux/tree/flow - feel free to fork + contribute!

**Comment by bcherny** [comment]
Published as 3.1.0. @ummahusla @niieani @frontsideair @gabiaxel Please let me know if you run into any issues!
