### ISSUE TITLE
React won't re-render when modifying store object or arrays 

### ISSUE THREAD

**Issue by DeanKamali** [bcherny/undux#53]
I have noticed the following behavior  

If I set an array or object as a value to given key in the store, 

```
var currentTime = new Date();
let store = withReduxDevtools(
  createStore({
 calendar: {
      year: currentTime.getFullYear(),
      day: currentTime.getDate()
    }
  })
);
```

If I go about modifying key property year or day inside the store, following this pattern. 

```
 let store = this.props.store;
 
// pull calendar object off the store and update it. 
 let calendar = store.get('calendar');
 calendar.year = 2020;

// update the store
store.set('calendar')(calendar);
```
In Redux tools, I see the object getting updated, yet react component won't re-render, therefore I had to add a hacky setState to force re-render and make it work. 

```
 this.setState({  test : Math.random() })
```
am I  doing something wrong here? 

Thanks

**Comment by bcherny** [comment]
Hey @DeanKamali! This is something we should do a better job of documenting. As a performance optimization, Undux checks that the value of `store.get(key) !== updatedStore.get(key)`; if the two are equal, then Undux does not re-render.

The fix here is to avoid mutating your object. A few ways to do that:

```js
let calendar = store.get('calendar');

// Option 1: Object.assign
store.set('calendar')(Object.assign({}, calendar, { year: 2020}));

// Option 2: Spread
store.set('calendar')({...calendar, year: 2020});

// Option 3: Immutable.Map
store.set('calendar')(
  calendar.set('year', 2020)
);
```

If you go with Option 3, you'll have to update `calendar`'s type in your store from a regular JavaScript object to an `Immutable.Map` (see https://facebook.github.io/immutable-js/docs/#/Map).
