### ISSUE TITLE
Having typing error with typescript and Store.withStore()

### ISSUE THREAD

**Issue by johhansantana** [bcherny/undux#54]
![image](https://user-images.githubusercontent.com/9933887/44163257-e2773c80-a090-11e8-982d-16fcfb12ba3a.png)

What can I do to fix this?

```
Argument of type 'typeof App' is not assignable to parameter of type 'ComponentType<{ store: Store<{ one: number; two: number; }>; }>'.
  Type 'typeof App' is not assignable to type 'StatelessComponent<{ store: Store<{ one: number; two: number; }>; }>'.
    Type 'typeof App' provides no match for the signature '(props: { store: Store<{ one: number; two: number; }>; } & { children?: ReactNode; }, context?: any): ReactElement<any>'.
```

**Comment by bcherny** [comment]
Hey @johhansantana! Do you have a more complete repro case? Can you copy + paste the source for that file and your store? (or even better, a minimally reproducible version of it)

**Comment by johhansantana** [comment]
I made this example:

```tsx
import * as React from 'react';
import Store from "../store";

interface Props {
  hello: any;
}

const Example = (props: Props) => (
  <p>{props.hello}</p>
);

export default Store.withStore(Example);
```

the store is this one

```ts
import { createConnectedStore } from "undux";

// Create a store with an initial value.
export default createConnectedStore({
  one: 0,
  two: 0
});
```

**Comment by johhansantana** [comment]
just noticed if I don't put the `interface` declaring `Props` it doesn't give me the error.

Must be something to do with adding `Store` to the `interface` but it wants an argument.

If I import `{Store} from 'undux'` and add it as `store: Store<any>` it works but I'm not sure if this is the right way.

```tsx
import * as React from 'react';
import { Store } from "undux";
import GlobalStore from "../store";

interface Props {
  hello: any;
  store: Store<any>
}

const Example = (props: Props) => (
  <p>{props.hello}</p>
);

export default GlobalStore.withStore(Example);
```

**Comment by bcherny** [comment]
Yup, you need to declare a `store` props. See https://undux.org/#examples/stateless-component-with-props

**Comment by johhansantana** [comment]
https://github.com/bcherny/undux#creating-a-store-typescript

just saw this... sorry for the noise, thanks @bcherny
