### ISSUE TITLE
Why do you develop alpha version on master branch?

### ISSUE THREAD

**Issue by 1natsu172** [bcherny/undux#57]
Hi. I appreciate the development of undux.

As a simple question, why are you developing the alpha version on the master branch? Do you have any special reasons?
Similarly, publishing to npm doesn't use the alpha tag. So alpha version is installed with `npm install undux` command.

I regularly keep track of this repository's commit logs and issues, so I notice changes in the API and master are alpha versions. But many people are not. Especially I think that it will cause confusion for people who use undux for the first time.

**Comment by bcherny** [comment]
Hey @1natsu172! To be honest, it was an oversight 🤭

The changes are backwards-compatible, so it should have been developed on another branch, then shipped as a a minor bump.
