### ISSUE TITLE
How should i use "onAll" at root store when i use namespaced state?

### ISSUE THREAD

**Issue by zonghow** [bcherny/undux#63]
![20180910033759.png](https://i.loli.net/2018/09/10/5b9576a130bb7.png)
![20180910034046.png](https://i.loli.net/2018/09/10/5b9577481d501.png)

**Comment by bcherny** [comment]
Hey @zonghow! You're almost there

```ts
export interface State {
  app: AppState
}

export type StoreEffects = EffectsAs<State>

export const effects: StoreEffects = (s) => {
  appEffects(s)
  withReduxDevtools(s.app)
  return s
}
```

If you want, you could update `withReduxDevtools` to accept either a `store` or a namespaced store -- PRs are welcome!

**Comment by zonghow** [comment]
If like this.
```
withReduxDevtools(s.app)
```
When s.otherStore changed, redux devtool can not capture this change.

It doesn't work even add this:
```
withReduxDevtools(s.otherStore)
```

**Comment by bcherny** [comment]
That’s surprising - do you think you could post a self contained repro case (eg. On stackblitz)? That sounds like a bug.

**Comment by bcherny** [comment]
That’s surprising - do you think you could post a self contained repro case (eg. On stackblitz)? That sounds like a bug.

**Comment by zonghow** [comment]
https://stackblitz.com/edit/undux-quick-start-typescript-8bstzx

**Comment by bcherny** [comment]
@zonghow This works fine for me locally. Did you:

- Enable Redux devtools extension

<img width="429" alt="screen shot 2018-09-11 at 8 48 49 pm" src="https://user-images.githubusercontent.com/1761758/45401177-46474380-b604-11e8-865c-50cd744f64f1.png">

- Give it access to file URLs
<img width="725" alt="screen shot 2018-09-11 at 8 48 55 pm" src="https://user-images.githubusercontent.com/1761758/45401182-4ba48e00-b604-11e8-8aad-443fb5f5c9c4.png">

- Choose Autoselect instances in Redux Devtools
<img width="178" alt="screen shot 2018-09-11 at 8 49 27 pm" src="https://user-images.githubusercontent.com/1761758/45401186-54955f80-b604-11e8-99da-02489b71efb9.png">
