### ISSUE TITLE
createConnectedStore arguments 

### ISSUE THREAD

**Issue by DeanKamali** [bcherny/undux#81]
Hey everyone, 

Forgive my ignorance, I'm wondering how I can get `withReduxDevtools` plugin to work while passing optional  `withEffects`

withReduxDevtools plugin works here 
`
export default createConnectedStore(initialState, withReduxDevtools)`

it doesn't work
`export default createConnectedStore(initialState, withEffects, withReduxDevtools)`

Any idea how I can get `withReduxDevtools` plugin to work along with `withEffects`?

**Comment by bcherny** [comment]
Sorry for the delayed response.

```js
export default createConnectedStore(initialState, s =>
  withReduxDevtools(withEffects(s))
)
```
