### ISSUE TITLE
How to use withLogger with namespaced state and effects?

### ISSUE THREAD

**Issue by AfflatusX** [bcherny/undux#82]
Looks like withLogger only takes single store definition?

**Comment by bcherny** [comment]
It's a little ugly, but you can do something like:

```
createConnectedStoreAs(initialStates, stores => {
  return withEffects({
    a: withLogger(stores.a),
    b: withLogger(stores.b)
  })
})
```

`createConnectedStoreAs`'s second argument is any function that takes an object of stores, and returns an object of stores.
