### ISSUE TITLE
using multiple stores

### ISSUE THREAD

**Issue by sirpy** [bcherny/undux#86]
The current suggestion to use nested stores doesn't allow same component to use two different stores.
The suggestion to use namespacing removes the separation of concerns possibility and will cause rerender in components needing only one store.

Using two stores seems to be working use react hooks ie useStore, but withStore doesn't seem to support composing. Any solution for that?

**Comment by bcherny** [comment]
Hey there! You have a few options:

1. Use `useStore` (preferred)
2. Use `createConnectedStoreAs`. See https://undux.org/#examples/namespaced-state
