### ISSUE TITLE
consider removing rxjs-observable

### ISSUE THREAD

**Issue by jeremy-coleman** [bcherny/undux#87]
i copy and pasted undux into my src folder, removed undux and rxjs-observable from package.json, then replaced rxjs-observable with rxjs. bundle size 18kb smaller according to webpack. rxjs version 6.5.2. I'm only doing webpack --production --optimizie-minimize, nothing fancy

**Comment by bcherny** [comment]
Thanks for the feedback!

RxJS is really big, unless you use a tree shaking bundler or tag RxJS as an external dependency in your build system. I want to try and strike a balance between small bundle sizes for people that use tree shaking bundlers and for people that don't.

To that end, RxJS-Observable was a bit of a hack to support both use cases. For people that don't use a tree shaking bundler, Undux comes with a minimal RxJS-compatible Observable implementation out of the box; for people that do tree shake, they have to eat the cost of a slightly larger bundle.

We could maybe ship two versions, one that uses RxJS directly and one that uses RxJS-Observable. I worry that it may not be obvious to people which one to use, though.

Any ideas? :)

**Comment by jeremy-coleman** [comment]
i think at some point in the v6 release they restructured the folders so that importing observable shouldn't bring in the whole lib , even without tree shaking, unless you manually import something deep into the folders.

A workaround though, would be to put rxjs as a peer dependency and put some instructions on how to shim rxjs with rxjs-obserable by installing it as rxjs:'git://bcheryn/rxjs-observable' in the package json. this also ensures users only have 1 copy of their choosing.

**Comment by bcherny** [comment]
> i think at some point in the v6 release they restructured the folders so that importing observable shouldn't bring in the whole lib , even without tree shaking, unless you manually import something that's deep into the folders.

Unfortunately, not quite. https://github.com/ReactiveX/rxjs/issues/4011, https://github.com/ReactiveX/rxjs/issues/3971#issuecomment-408696661

We could add it as a peer dependency, potentially. That said, `rxjs-obserable` is really small -- are you noticing real performance issues in your app while using it?

**Comment by jeremy-coleman** [comment]
No, its not a big deal honestly, i just thought that the duplication was unneccessary and 2 copies could lead to wierd things happening. Also, in my unionformed opinion, i dont know why anyone would use an rx observable without rx operators
