### ISSUE TITLE
React Native "createStore is not a function"

### ISSUE THREAD

**Issue by edilsalvador** [bcherny/undux#91]
I'm having trouble setting up undux on my React Native project.
`createStore` is deprecated in version `5.0.0` as stated in the website, but I follow exactly what is in the documentation setup.

What is the recommended way to set the undux store globally?

Here's my module versions:
```
    "react": "16.9.0",
    "react-native": "0.61.5",
    "undux": "^5.0.0-beta.22"
    "rxjs": "^6.5.3",
```

Here's my sample code:
```
import React from 'react';
import { View, Text } from 'react-native';
import { createConnectedStore } from 'undux';

const Store = createConnectedStore({
  data: [],
});

export default function App() {
  return (
    <Store.Container>
      <View style={{ flex: 1 }}>
        <Text style={{ color: '#000' }}>
          Hello World!
        </Text>
      </View>
    </Store.Container>
  );
}
```
Sample Screenshot:

![Screenshot_1575193930](https://user-images.githubusercontent.com/17653666/69912361-59417000-1463-11ea-91be-2759a073e1b5.png)

**Comment by bcherny** [comment]
Hey there @edilsalvador! Undux works on RN, so there's probably an issue with the way Undux is getting built in your project.

How are you building your project? I'd start by debugging why `__1` is `undefined` (maybe log it out?).

**Comment by edilsalvador** [comment]
Hi @bcherny, thanks for pointing that out. I tried to setup undux to another react-native init project and now it works. Not really sure what was the problem on my previous setup. Thanks again! :rocket:
