### ISSUE TITLE
withLogger - slowing down UI rendering

### ISSUE THREAD

**Issue by DeanKamali** [bcherny/undux#92]
I have noticed that when a change that affects 5 or more keys will slow down UI rendering, 
UI rendering speed is fine when logging is disabled. 

I understand that logging should be disabled in production, just wondering if there is a way to overcome this issue.

**Comment by bcherny** [comment]
Hey there @DeanKamali! While I haven't seen this issue before, it sounds like you might be stringifying really big objects.

How big are the objects you're logging?

**Comment by DeanKamali** [comment]
Yes, it was a big object 20+ keys, I don't think its a big deal, will be closing this issue for now.

**Comment by jeremy-coleman** [comment]
Its Probably bc ur devtool are open. Try closing them and see if its still slow. U could also batch the writes
